apiVersion: v1
kind: Secret
metadata:
  name: qa-secret
  namespace: dev
  labels:
    app: cinescope-grpc
type: Opaque
stringData:
  # PostgreSQL connection string
  # Format: postgresql://username:password@host:port/database
  DATABASE_URL_POSTGRES: "postgresql://postgres:AmwFrtnR2@postgres:5432/db_movies"
